<div class="cat2-block">
<img class="desktop" src="{{media url="bannerimage/block2img.jpg"}}">
<img class="mobile" style="display:none;" src="{{media url="bannerimage/block2img.jpg"}}">
<div class="block-cont left">
<p class="small-cont">Our Latest Pro Glove Series</p>
<p class="cat-cont big">FOR PLAYERS. <br>BY PLAYERS.</p>
</div>
<a class="shopbtn left sec" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-gloves.html">shop now !</a></div>