-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 04, 2021 at 02:48 AM
-- Server version: 10.2.40-MariaDB-log-cll-lve
-- PHP Version: 7.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `m2sportszonecana_newv3`
--

-- --------------------------------------------------------

--
-- Table structure for table `cms_block`
--

CREATE TABLE `cms_block` (
  `block_id` smallint(6) NOT NULL COMMENT 'Entity ID',
  `title` varchar(255) NOT NULL COMMENT 'Block Title',
  `identifier` varchar(255) NOT NULL COMMENT 'Block String Identifier',
  `content` mediumtext DEFAULT NULL COMMENT 'Block Content',
  `creation_time` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Block Creation Time',
  `update_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Block Modification Time',
  `is_active` smallint(6) NOT NULL DEFAULT 1 COMMENT 'Is Block Active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CMS Block Table';

--
-- Dumping data for table `cms_block`
--

INSERT INTO `cms_block` (`block_id`, `title`, `identifier`, `content`, `creation_time`, `update_time`, `is_active`) VALUES
(1, 'Footer Links', 'block_footer_custom', '<div class=\"footer-custom\">\r\n<div class=\"footer-content\">\r\n<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n<p class=\"footer-title\">ACCOUNT</p>\r\n<ul class=\"footer-v3-list\">\r\n<li><a href=\"{{store url=\"customer/account/\"}}\">My Account</a></li>\r\n<li><a href=\"{{store url=\"sales/order/history/\"}}\">Order History</a></li>\r\n<li><a href=\"{{store url=\"wishlist/\"}}\">Wish List</a></li>\r\n<li><a href=\"{{store url=\"\"}}\">Specials</a></li>\r\n</ul>\r\n</div>\r\n<!-- FOOTER COLUMN #1 END --> <!-- FOOTER COLUMN #2 BEGIN -->\r\n<div class=\"col-md-3 col-sm-6 col-xs-12 \">\r\n<p class=\"footer-title\">DEPARTMENTS</p>\r\n<ul class=\"footer-v3-list\">\r\n<li><a href=\"{{store url=\"team-sports-hockey.html\"}}\">Hockey</a></li>\r\n<li><a href=\"{{store url=\"goalie.html\"}}\">Goalie</a></li>\r\n<li><a href=\"{{store url=\"baseball.html\"}}\">Base Ball</a></li>\r\n<li><a href=\"{{store url=\"team-sports.html\"}}\">Other Sports</a></li>\r\n<li><a href=\"{{store url=\"figure-skating.html\"}}\">Figure Skating</a></li>\r\n<li><a href=\"{{store url=\"team-wear.html\"}}\">Team Wear</a></li>\r\n</ul>\r\n</div>\r\n<!-- FOOTER COLUMN #2 END --> <!-- FOOTER COLUMN #3 BEGIN -->\r\n<div class=\"col-md-3 col-sm-6 col-xs-12 \">\r\n<p class=\"footer-title\">SERVICES</p>\r\n<ul class=\"footer-v3-list\">\r\n<li><a href=\"{{store url=\"returns\"}}\">Discount Returns</a></li>\r\n<li><a href=\"{{store url=\"privacy-policy-cookie-restriction-mode\"}}\">Policy</a></li>\r\n<li><a href=\"{{store url=\"customer-service\"}}\">Customer Service</a></li>\r\n<li><a href=\"{{store url=\" \"}}\">Term &amp; condition</a></li>\r\n</ul>\r\n</div>\r\n<!-- FOOTER COLUMN #3 END --> <!-- FOOTER COLUMN #4BEGIN -->\r\n<div class=\"col-md-3 col-sm-6 col-xs-12 \">\r\n<p class=\"footer-title\">INFO</p>\r\n<ul class=\"footer-v3-list\">\r\n<li><a href=\"{{store url=\"about-us\"}}\">About us</a></li>\r\n<li><a href=\"{{store url=\"\"}}\">FAQ</a></li>\r\n<li><a href=\"{{store url=\"shipping\"}}\">Delivery Information</a></li>\r\n<li><a href=\"{{store url=\"contacts\"}}\">Contact us</a></li>\r\n</ul>\r\n</div>\r\n<!-- FOOTER COLUMN #4 END -->\r\n<div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n<p class=\"footer-title\">LOCATION</p>\r\n<ul class=\"footer-v3-list address\">\r\n<li>92 Lodge Street</li>\r\n<li>Waterloo, ON N2J 2V6 Canada</li>\r\n<li>T: 1-888-785-9818</li>\r\n<li>F: 519-489-4041</li>\r\n<li>info@sportszonecanada.com</li>\r\n<li>\r\n<div class=\"pull-right-md social-icons-v1\">\r\n                <a href=\"https://twitter.com/sportzonecanada\" class=\"fa fa-twitter si-borderless si-twitter\"></a>\r\n                <a href=\"https://www.facebook.com/sportzonecanada/\" class=\"fa fa-facebook si-borderless si-facebook\"></a>\r\n  </div>\r\n</li>\r\n</ul>\r\n</div>\r\n</div>\r\n</div>', '2014-02-14 06:08:03', '2021-01-16 05:40:55', 1),
(2, 'Cookie restriction notice', 'cookie_restriction_notice_block', '<p>This website requires cookies to provide all of its features. For more information on what data is contained in the cookies, please see our <a href=\"{{store direct_url=\"privacy-policy-cookie-restriction-mode\"}}\">Privacy Policy page</a>. To accept cookies from this site, please click the Allow button below.</p>', '2014-02-14 06:08:03', '2017-01-06 21:08:50', 1),
(3, 'Top Static Links', 'top-static-links', '<div class=\"custom-top-header\">\r\n<div class=\"custom-top-head1\">\r\n<ul class=\"custom-header-links\">\r\n<li class=\"first-menu\"><i class=\"fa fa-chevron-down\" style=\"color:#fff\"></i><a title=\"Company\" href=\"{{store url=\'customer-support}}\"> Customer Support</a>\r\n<div class=\"support-menu\">\r\n<ul class=\"sub-header\">\r\n<li><a href=\"{{store url=\'about-us\'}}\">About</a></li>\r\n<li><a href=\"{{store url=\'in-store-service\'}}\">In Store Service</a></li>\r\n<li><a href=\"{{store url=\'contacts\'}}\">Contact Us</a></li>\r\n<li><a href=\"{{store url=\'price-match\'}}\">Price Match</a></li>\r\n<li><a href=\"{{store url=\'shipping\'}}\">Shipping</a></li>\r\n<li><a href=\"{{store url=\'returns\'}}\">Returns &amp; Refunds</a></li>\r\n</ul>\r\n</div>\r\n&emsp;|</li>\r\n<li><i class=\'fa fa-male\' style=\"color:#fff\"></i><a title=\"Customer Team Wear\" href=\"{{store url=\'custom-team-wear\'}}\"> Custom Team Wear</a>&emsp;|</li>\r\n<li><i class=\"fa fa-money\" style=\"color:#fff\"></i><a title=\"Rewards\" href=\"{{store url=\'rewards\'}}\"> Rewards</a>&emsp;|</li>\r\n<li><i class=\'fa fa-volume-off\' style=\"color:#fff\"></i><a title=\"Blog\" href=\"{{store url=\'blog\'}}\"> Blog</a>&emsp;|</li>\r\n<li><i class=\"fa fa-clock-o\" style=\"color:#fff\"></i><a title=\"Hours\" href=\"{{store url=\'hours\'}}\"> Hours</a></li>\r\n</ul>\r\n<div class=\"right\">\r\n<ul class=\"social-links links\">\r\n<li class=\"custom-mob\"><span ><i class=\"fa fa-headphones\" aria-hidden=\"true\"></i>1-888-785-9818</span></li>\r\n<li class=\"first left\">\r\n                  <a href=\"http://www.facebook.com/pages/SportZone-Canada/132325396786190\" target=\"_blank\" class=\"fa fa-facebook si-borderless si-facebook\"></a>\r\n            </li>\r\n            <li class=\"left\">\r\n               <a href=\"https://twitter.com/sportzonecanada\" target=\"_blank\" class=\"fa fa-twitter si-borderless si-twitter\"></a>\r\n            </li>\r\n<li class=\"left\">\r\n               <a href=\"https://instagram.com/sportzonecanada\" target=\"_blank\" class=\"fa fa-instagram si-borderless si-instagram\"></a>\r\n            </li>\r\n<li><img src=\"{{media url=\"headericon/paym.png\"}}\" alt=\"Credit Cards / PayPal\"></li>\r\n</ul>\r\n</div>\r\n</div>\r\n</div>', '2014-02-21 02:56:26', '2020-11-02 05:43:20', 1),
(4, 'Social Links', 'social-links', '<ul class=\"social-links links\">\r\n<li class=\"first left\">\r\n    <a href=\"http://www.facebook.com/pages/SportZone-Canada/132325396786190\" target=\"_blank\">\r\n        <i class=\"icon-facebook\"></i>\r\n    </a>\r\n</li>\r\n<li class=\"left\">\r\n    <a href=\"https://twitter.com/sportzonecanada\" target=\"_blank\">\r\n        <i class=\"icon-twitter\"></i>\r\n    </a>\r\n</li>\r\n</ul>', '2014-02-21 03:47:59', '2017-01-06 21:09:21', 1),
(5, 'Store Hours', 'store-hours', '<div class=\"std\">\r\n<p><span style=\"font-size: x-large;\"><strong>Open For instore Shopping</strong></span></p>\r\n<p><span style=\"font-size: x-large;\"><strong></strong></span><span style=\"font-size: x-large;\"><strong>Respecting Capacity limitations&nbsp;<strong>outlined by Covid-19 Guidelines</strong></strong></span></p>\r\n<p><span style=\"font-size: x-large;\"></span><span style=\"font-size: x-large;\"><span style=\"font-size: medium;\">Appointments are available but not necessary&nbsp; -to book an appointment use the toggle at the side of the home page</span></span></p>\r\n<p><span style=\"font-size: x-large;\"></span><span style=\"font-size: x-large;\"><span style=\"font-size: medium;\"> CLOSED MONDAY OCT 12 FOR THANKSGIVING</span></span></p>\r\n<p><strong style=\"font-size: large;\">Mon:&nbsp; 11am to 7pm<strong><br /></strong></strong></p>\r\n<p><strong style=\"font-size: large;\">Tue: &nbsp;<strong>11am to 7pm</strong></strong></p>\r\n<p><span style=\"font-size: large;\"><strong>Wed:&nbsp;<strong>11am to 8pm</strong></strong></span></p>\r\n<p><span style=\"font-size: large;\"><strong>Thur: 11am to 8pm<strong><br /></strong></strong></span></p>\r\n<p><span style=\"font-size: large;\"><strong>Fri:&nbsp; 11am to 8pm<strong><br /></strong></strong></span></p>\r\n<p><span style=\"font-size: large;\"><strong>Sat:10am to 5pm<strong><br /></strong></strong></span></p>\r\n<p><span style=\"font-size: large;\"><strong>Sun: 12pm to 4pm</strong></span></p>\r\n</div>', '2014-02-26 01:37:11', '2020-10-17 07:34:56', 1),
(6, 'Store Fax', 'store-fax', 'F: 519-489-4041', '2014-02-26 03:48:29', '2017-01-06 21:09:36', 1),
(7, 'Contact Information', 'contact-information', '{{block class=\"Magento\\Contact\\Block\\ContactForm\" name=\"contactForm\" template=\"Magento_Contact::form.phtml\"}}\r\n<div class=\"block\">\r\n    <div class=\"block-title\">\r\n        Contact Information\r\n    </div>\r\n    <div class=\"block-content\">\r\n        <ul class=\"contact-list clearer\">\r\n				<li class=\"clearer\">\r\n					<div class=\"left\"><i class=\"icon-location\"></i></div>\r\n					<div class=\"left contact-list-content\">\r\n                                            <div class=\"contact-list-title\">Store Location</div>\r\n                                            <div>{{config path=\"general/store_information/address\"}}</div>\r\n                                        </div>\r\n				</li>\r\n			    <li class=\"clearer\">\r\n				    <div class=\"left\"><i class=\"icon-mail\"></i></div>\r\n				    <div class=\"left contact-list-content\">\r\n                                        <div class=\"contact-list-title\">Email</div>\r\n                                        <div><a href=\"mailto:{{config path=\"trans_email/ident_general/email\"}}\">{{config path=\"trans_email/ident_general/email\"}}</a></div>\r\n			    </li>\r\n			    <li class=\"clearer\">\r\n				    <div class=\"left\"><i class=\"icon-phone\"></i></div>\r\n				    <div class=\"left contact-list-content\">\r\n                                            <div class=\"contact-list-title\">Telephone</div>\r\n					    <div><a href=\"tel:\"{{config path=\"general/store_information/phone\"}}\">{{config path=\"general/store_information/phone\"}}</a></div>\r\n					</div>\r\n			    </li>\r\n			    <li class=\"clearer\">\r\n				    <div class=\"left\"><i class=\"icon-print\"></i></div>\r\n				    <div class=\"left contact-list-content\">\r\n                                            <div class=\"contact-list-title\">Fax</div>\r\n					    <div>519-489-4041</div>\r\n					</div>\r\n			    </li>\r\n			    <li class=\"clearer last\">\r\n				    <div class=\"left\"><i class=\"icon-clock\"></i></div>\r\n				    <div class=\"left contact-list-content\">\r\n                                            <div class=\"contact-list-title\">Hours of Operation</div>\r\n				             {{block type=\"cms/block\" block_id=\"store-hours\" template=\"content.phtml\"}} \r\n			       </div>\r\n			    </li>\r\n		    </ul>\r\n    </div>\r\n</div>', '2014-02-27 05:03:42', '2020-10-17 07:56:01', 1),
(8, 'Top Mobile Links', 'top-mobile-links', '<ul class=\"links\">\r\n<li class=\"first\"><a title=\"My Account\" href=\"{{store url=\'customer/account\'}}\"> <i class=\"icon-user\"></i><span>My Account</span></a></li>\r\n<li><a title=\"Checkout\" href=\"{{store url=\'checkout}}\"> <i class=\"icon-money\"></i><span>Checkout</span></a></li>\r\n\r\n<li><a title=\"Customer Support\" href=\"{{store url=\'contacts\'}}\"> <i class=\"icon-cog\"></i><span>Customer Support</span></a></li>\r\n\r\n<li><a title=\"My Wishlist\" href=\"{{store url=\'wishlist\'}}\"> <i class=\"icon-heart\"></i><span>My Wishlist</span></a></li>\r\n<li><a title=\"About Us\" href=\"{{store direct_url=\'about-us}}\"> <i class=\"icon-home\"></i><span>About Us</span></a></li>\r\n\r\n<li><a title=\"Rewards\" href=\"{{store url=\'blog\'}}\"> <i class=\"icon-megaphone\"></i><span>Blog</span></a></li>\r\n<li class=\"social clearer\">\r\n<span class=\"left\">\r\nSocial Media &nbsp;&nbsp;|\r\n</span>\r\n    <a href=\"http://www.facebook.com/pages/SportZone-Canada/132325396786190\">\r\n        <i class=\"icon-facebook\"></i>&nbsp;\r\n    </a>\r\n    <a href=\"https://twitter.com/sportzonecanada\">\r\n        <i class=\"icon-twitter\"></i>\r\n    </a>\r\n</li>\r\n</ul>', '2014-05-02 23:07:01', '2017-01-06 21:47:13', 1),
(9, 'Rewards Banner', 'rewards-banner', '<div class=\"rewards-points-banner\">\r\n<div class=\"images clearfix\">\r\n<img src=\"{{media url=\"wysiwyg/spend-and-earn.jpg\"}}\" alt=\"Spend and Earn\"/>\r\n<img src=\"{{media url=\"wysiwyg/10-dollars.jpg\"}}\" alt=\"10 dollars\" />\r\n<img src=\"{{media url=\"wysiwyg/redeem_points.jpg\"}}\" alt=\"Redeem Points\" />\r\n</div>\r\n</div>', '2015-01-14 19:16:03', '2017-01-06 21:12:02', 1),
(10, 'Unbeatable Prices Banner', 'unbeatable-prices-banner', '<div class=\"unbeatable-prices-banner\">\r\n<img src=\"{{media url=\"wysiwyg/login_banner.jpg\"}}\" alt=\"Login\"/>\r\n</div>', '2015-01-29 20:46:28', '2017-01-06 21:12:08', 1),
(11, 'Age Gate', 'vsourz-age-gate', '<div class=\"sitelogo\">LOGO</div>\n<h2>This Website requires you to be 18 years or older to enter.</h2>', '2018-10-12 09:39:29', '2018-10-12 09:39:29', 1),
(12, 'Age Gate Disagree', 'vsourz-age-gate-disagree', '<div class=\"sitelogo\">LOGO</div>\n<h2>Sorry Adults Only</h2>', '2018-10-12 09:39:29', '2018-10-12 09:39:29', 1),
(13, 'Team Wear', 'team_wear', '<div><img src=\"{{media url=&quot;wysiwyg/team-predators.jpg&quot;}}\" alt=\"Predators\"></div>\r\n<div class=\"category-title\"><a href=\"https://predators-2019-spirit-wear.itemorder.com/closed\" target=\"_blank\" rel=\"noopener\"> TWIN CITY FOOTBALL </a></div>\r\n<div><img src=\"{{media url=&quot;wysiwyg/team-waterloo-wolves.jpg&quot;}}\" alt=\"Waterloo Wolves\"></div>\r\n<div class=\"category-title\"><a href=\"https://2019waterloowolves.itemorder.com/sale\" target=\"_blank\" rel=\"noopener\"> Waterloo Wolves</a></div>\r\n<div><img src=\"{{media url=&quot;wysiwyg/team-waterloo-ravens.jpg&quot;}}\" alt=\"Waterloo Ravens\"></div>\r\n<div class=\"category-title\"><a href=\"https://2019waterlooravens.itemorder.com/sale\" target=\"_blank\" rel=\"noopener\"> Waterloo Ravens </a></div>\r\n<div><img src=\"{{media url=&quot;wysiwyg/team-woolwich.jpg&quot;}}\" alt=\"Woolwich Wildcats\"></div>\r\n<div class=\"category-title\"><a href=\"https://2019woolwichwildcats.itemorder.com/sale\" target=\"_blank\" rel=\"noopener\"> Woolwich Wildcats</a></div>\r\n<div><img src=\"{{media url=&quot;wysiwyg/team-wilmot-wolverines.jpg&quot;}}\" alt=\"Wolverines\"></div>\r\n<div class=\"category-title\"><a href=\"https://wilmotwolverinesspiritwear2019.itemorder.com/sale\" target=\"_blank\" rel=\"noopener\"> WOLVERINES </a></div>\r\n<div><img src=\"{{media url=&quot;wysiwyg/Huskies.jpg&quot;}}\" alt=\"Wolverines\" width=\"188\" height=\"197\"></div>\r\n<div class=\"category-title\"><a href=\"https://2019newhamburghuskies.itemorder.com/sale\" target=\"_blank\" rel=\"noopener\"> HUSKIES </a></div>', '2019-11-07 04:25:57', '2021-03-16 21:44:41', 1),
(14, 'Goalie Customization', 'goalie_customization', '<div style=\"clear: both;\"></div>\r\n<p style=\"text-align: center;\"><button class=\"button\" onclick=\"window.open(\'https://www.sportszonecanada.com/goalie-customizers\')\" title=\"Pro Customizers\" type=\"submit\"><span><span>Pro Customizers</span></span></button>&nbsp;&nbsp;&nbsp;</p>\r\n<p style=\"text-align: center;\"></p>\r\n<p style=\"text-align: center;\"></p>', '2019-11-20 04:20:55', '2019-12-13 06:29:57', 1),
(15, 'Goalie Pad Block', 'goal-pad-block', '<p><img alt=\"\" height=\"263\" src=\"{{media url=\"wysiwyg/price.jpg\"}}\" style=\"display: block; margin-left: auto; margin-right: auto;\" width=\"531\" /></p>', '2020-02-04 22:11:04', '2020-02-04 22:11:48', 1),
(16, 'Newsletter block', 'newsleter-block', '<div class=\"news-overlay\">\r\n<p>Get instant access to SportsZone Rewards news,</p>\r\n<p>sale information and more!</p>\r\n{{block class=\"Magento\\Newsletter\\Block\\Subscribe\" name=\"static.newsletter\" template=\"Magento_Newsletter::subscribe.phtml\"}}</div>', '2020-10-06 12:37:23', '2020-10-06 12:37:23', 1),
(17, 'Free shipping', 'free-shiplabel', '<p class=\"custom-freeship\"><img src=\"{{media url=\"banners/Free_Shipping_Banner.jpg\"}}\" alt=\"Free Shipping On Orders Over 100 Dollars\"></p>', '2020-10-06 12:38:07', '2021-03-12 05:32:26', 1),
(18, 'Home banner', 'banner-slider', '<div class=\"homeSlider\">\r\n<div class=\"item\"><img src=\"{{media url=&quot;banners/BAUER_MASK_BOGO_SALE.jpg&quot;}}\" alt=\"Bauer Facemasks Bogo Sale\">\r\n<div class=\"banner-txt\">&nbsp;</div>\r\n<div class=\"banner-txt\">&nbsp;</div>\r\n<div class=\"banner-txt\" style=\"text-align: left;\"><a class=\"shop-banner\" href=\"{{store url=&quot;&quot;}}\">SHOP NOW !</a></div>\r\n</div>\r\n<div class=\"item\"><img src=\"{{media url=&quot;headericon/banner3.jpg&quot;}}\" alt=\"banner2\">\r\n<div class=\"banner-txt\">\r\n<p>Bauer Spreme Ultrasonic <br>Senior Hockey Skates</p>\r\n<a class=\"shop-banner\" href=\"{{store url=&quot;&quot;}}\">SHOP NOW !</a></div>\r\n</div>\r\n<div class=\"item\"><img src=\"{{media url=&quot;headericon/banner3.jpg&quot;}}\" alt=\"banner3\">\r\n<div class=\"banner-txt\">\r\n<p>Bauer Spreme Ultrasonic <br>Senior Hockey Skates</p>\r\n<a class=\"shop-banner\" href=\"{{store url=&quot;&quot;}}\">SHOP NOW !</a></div>\r\n</div>\r\n</div>', '2020-10-06 12:38:39', '2021-03-11 14:21:52', 1),
(19, 'Home banner mobile', 'banner-slider1', '<div class=\"homeSlider\">\r\n<div class=\"item\"><img src=\"{{media url=\"headericon/banner4.jpg\"}}\" alt=\"banner11\">\r\n<div class=\"banner-txt-mob\">\r\n<p>Bauer Spreme Ultrasonic <br>Senior Hockey Skates</p>\r\n<a class=\"shop-banner\" href=\"{{store url=\"\"}}\">SHOP NOW !</a></div>\r\n</div>\r\n<div class=\"item\"><img src=\"{{media url=\"headericon/banner4.jpg\"}}\" alt=\"banner12\">\r\n<div class=\"banner-txt-mob\">\r\n<p>Bauer Spreme Ultrasonic <br>Senior Hockey Skates</p>\r\n<a class=\"shop-banner\" href=\"{{store url=\"\"}}\">SHOP NOW !</a></div>\r\n</div>\r\n<div class=\"item\"><img src=\"{{media url=\"headericon/banner4.jpg\"}}\" alt=\"banner13\">\r\n<div class=\"banner-txt-mob\">\r\n<p>Bauer Spreme Ultrasonic <br>Senior Hockey Skates</p>\r\n<a class=\"shop-banner\" href=\"{{store url=\"\"}}\">SHOP NOW !</a></div>\r\n</div>\r\n</div>', '2020-10-06 12:39:18', '2020-10-06 12:39:18', 1),
(20, 'Top mobile menu', 'top-mobile-menu', '<div class=\"custom-topmenu-m\"><span class=\"custom-topno-m\"><i class=\"fa fa-headphones\" aria-hidden=\"true\"></i>1-888-785-9818</span>\r\n<div data-block=\"minicart\" class=\"minicart-wrapper\" id=\"custom-mobile-cart\">\r\n<a class=\"action showcart\" href=\"{{store url=\"checkout/cart/\"}}\" data-bind=\"scope: \'minicart_content\'\"> <img class=\"custom-user\" src=\"{{media url =\"headericon/cartcustom2.png\"}}\"> <span class=\"text\">My Cart</span> <span class=\"counter qty empty\" data-bind=\"css: { empty: !!getCartParam(\'summary_count\') == false &amp;&amp; !isLoading() }, blockLoader: isLoading\"> \r\n<span class=\"counter-number\"><!-- ko text: getCartParam(\'summary_count\') --><!-- /ko --></span> \r\n<span class=\"counter-label\"> \r\n<!-- ko if: getCartParam(\'summary_count\') -->\r\n <!-- ko text: getCartParam(\'summary_count\') -->\r\n <!-- /ko --> <!-- ko i18n: \'items\' --> <!-- /ko --> <!-- /ko --> \r\n </span>\r\n</span> \r\n        <!-- ko if: getCartParam(\'summary_count\') -->\r\n       <span class=\"custom-mini-price\" data-bind=\"html: getCartParam(\'subtotal\')\"></span> \r\n        <!-- /ko -->\r\n        <!-- ko ifnot: getCartParam(\'summary_count\') -->\r\n        <span class=\"custom-mini-price\">$0.00</span> \r\n        <!-- /ko -->\r\n</a></div>\r\n</div>', '2020-10-06 12:39:56', '2021-06-28 08:02:08', 1),
(21, 'sale block 1', 'sale-block-1', '<div class=\"cat1-block\">\r\n<div class=\"cat1-block1\">\r\n<div class=\"cat11-block\"><img src=\"{{media url=\"bannerimage/block1img1.jpg\"}}\">\r\n<div class=\"block-cont firstbk\">\r\n<p class=\"cat-cont center\">Find the <br>Protech Stick</p>\r\n</div>\r\n<a class=\"shopbtn center firstbk\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey.html\">shop now !</a></div>\r\n<div class=\"cat11-block\"><img src=\"{{media url=\"bannerimage/block1img2.jpg\"}}\">\r\n<div class=\"block-cont center firstbk\">\r\n<p class=\"cat-cont\">Be Smart<br>Protech Your Head</p>\r\n</div>\r\n<a class=\"shopbtn center firstbk\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-helmets.html\">shop now !</a></div>\r\n</div>\r\n<div class=\"cat12-block\"><img src=\"{{media url=\"bannerimage/block1img3.jpg\"}}\">\r\n<div class=\"block-cont firstbk\">\r\n<p class=\"cat-cont \">Perfect Stick <br>for Perfect Shot</p>\r\n</div>\r\n<a class=\"shopbtn firstbk\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/composite-sticks.html\">shop now !</a></div>\r\n</div>\r\n<div class=\"cat14-block\"><img src=\"{{media url=\"bannerimage/block1img4.jpg\"}}\">\r\n<div class=\"block-cont center\">\r\n<p class=\"cat-cont left-bnr\">Covered from<br>Head to Toe</p>\r\n</div>\r\n<a class=\"shopbtn bottom firstbk\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/shoulder-pads.html\">shop now !</a></div>', '2020-10-06 12:40:43', '2021-01-16 05:21:21', 1),
(22, 'sale block 2', 'sale-block-2', '<div class=\"cat2-block\"><img src=\"{{media url=\"bannerimage/block2img.jpg\"}}\">\r\n<div class=\"block-cont left\">\r\n<p class=\"small-cont\">Our Latest Pro Glove Series</p>\r\n<p class=\"cat-cont big\">FOR PLAYERS. <br>BY PLAYERS.</p>\r\n</div>\r\n<a class=\"shopbtn left sec\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-gloves.html\">shop now !</a></div>', '2020-10-06 12:41:13', '2021-01-16 05:22:12', 1),
(23, 'sale block 3', 'sale-block-3', '<div class=\"cat3-block\"><img src=\"{{media url=\"bannerimage/block3img1.jpg\"}}\">\r\n<div class=\"block-cont\">\r\n<p class=\"cat-cont\">Find the <br>Perfect Gloves</p>\r\n</div>\r\n<a class=\"shopbtn\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-gloves.html\">shop now !</a></div>\r\n<div class=\"cat3-block\"><img src=\"{{media url=\"bannerimage/block3img2.jpg\"}}\">\r\n<div class=\"block-cont\">\r\n<p class=\"cat-cont \">Find the <br>Perfect Helmet</p>\r\n</div>\r\n<a class=\"shopbtn\" href=\"http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-helmets.html\">shop now !</a></div>', '2020-10-06 12:41:43', '2021-01-16 05:22:53', 1),
(24, 'policy section', 'policy-section', '<div class=\"policy1 bor-top\"><img class=\"policy-img\" src=\"{{media url=\"home/delivery.jpg\"}}\"> <span class=\"bold-content\">Fast shipping on time</span></div>\r\n<div class=\"policy1 center\"><img class=\"policy-img\" src=\"{{media url=\"home/return.jpg\"}}\"> <span class=\"bold-content\">Easy Return</span></div>\r\n<div class=\"policy1 right\"><img class=\"policy-img\" src=\"{{media url=\"home/security.jpg\"}}\"> <span class=\"bold-content\">Best Price Guarantee</span></div>', '2020-10-06 13:56:58', '2020-10-06 13:56:58', 1),
(25, 'Category Listing', 'category_list', '\r\n<div class=\"category-directory\">{{block class=\"Magento\\Framework\\View\\Element\\Template\" name=\"catalog.categories\" template=\"Magento_Catalog::navigation/category_listing.phtml\"}}</div>', '2020-10-14 10:30:24', '2020-11-27 05:38:21', 1),
(26, 'canada shipping', 'canada-shipping', '<div class=\"product-feature-detail last\" style=\"height: 66px;\">\r\n<div class=\"tooltip-on-icon\">Please note that due to shipping restrictions This product is unable to ship this item outside of Canada.</div>\r\n<img src=\"{{media url=\"headericon/circle-ca.png\"}}\">\r\n<p class=\"icon canada_only\">Ships Canada Only</p>\r\n</div>', '2020-10-20 05:28:01', '2020-10-20 06:09:26', 1),
(27, 'US shipping', 'us-shipping', '<div class=\"product-feature-detail last\" style=\"height: 66px;\">\r\n<div class=\"tooltip-on-icon\">Please note that due to shipping restrictions This product is unable to ship this item outside of US.</div>\r\n<img src=\"{{media url=\"headericon/circle-us.png\"}}\">\r\n<p class=\"icon us_only\">Ships US Only</p>\r\n</div>', '2020-10-20 05:29:00', '2020-10-20 06:09:38', 1),
(28, 'custom sider bar', 'custom_side_category_block', '<div class=\"custom-menu-filter\" style=\"width: 100%;\">{{widget type=\"Ves\\Megamenu\\Block\\Widget\\Menu\" title=\"Categories\" alias=\"category-menu\"}}</div>', '2020-10-23 04:55:47', '2020-10-23 04:55:47', 1),
(29, 'sale category filter', 'sale-category-filter', '<div class=\"sale-category\">{{widget type=\"Ves\\Megamenu\\Block\\Widget\\Menu\" title=\"CATEGORY\" alias=\"category-menu\"}}</div>', '2020-10-23 04:57:14', '2020-10-23 04:57:14', 1),
(30, 'Product shipping details', 'product-ship-detail', '<div class=\"custom-sdetail\">\r\n<p>\r\n<img src=\"{{media url=\"producticon/delivery-truck.png\"}}\">\r\n<span> Free Shipping $100+</span>\r\n</p>\r\n<p>\r\n<img src=\"{{media url=\"producticon/thumbs.png\"}}\">\r\n<span>Easy Returns</span>\r\n</p>\r\n<p>\r\n<img src=\"{{media url=\"producticon/tag.png\"}}\">\r\n<span>Price Guarantee</span>\r\n</p>\r\n</div>', '2020-11-02 08:50:17', '2020-11-10 11:07:00', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cms_block`
--
ALTER TABLE `cms_block`
  ADD PRIMARY KEY (`block_id`);
ALTER TABLE `cms_block` ADD FULLTEXT KEY `CMS_BLOCK_TITLE_IDENTIFIER_CONTENT` (`title`,`identifier`,`content`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cms_block`
--
ALTER TABLE `cms_block`
  MODIFY `block_id` smallint(6) NOT NULL AUTO_INCREMENT COMMENT 'Entity ID', AUTO_INCREMENT=31;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
