<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<head>
<style>
    .email-items .order-totals tr th,.email-items .order-totals tr td {text-align:right;}
    .email-items thead tr th,.email-items thead tr td {text-align:left;}
    .email-items thead tr th {text-align:left;background-color:#EAEAEA;font-size:13px;padding:3px 9px;}
</style>
</head>
<?php $_creditmemo = $block->getCreditmemo() ?>
<?php $_order      = $block->getOrder() ?>
<?php if ($_creditmemo && $_order) : ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-subtotal">
                    <?= $block->escapeHtml(__('Subtotal')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_creditmemo->getAllItems() as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('creditmemo_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
