<div class="cat3-block">
<img class="desktop" src="{{media url="bannerimage/block3img1.jpg"}}">
<img class="mobile"  style="display:none;" src="{{media url="bannerimage/block3img1.jpg"}}">
<div class="block-cont">
<p class="cat-cont">Find the <br>Perfect Gloves</p>
</div>
<a class="shopbtn" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-gloves.html">shop now !</a></div>
<div class="cat3-block">
<img class="desktop" src="{{media url="bannerimage/block3img2.jpg"}}">
<img class="mobile"  style="display:none;"src="{{media url="bannerimage/block3img2.jpg"}}">
<div class="block-cont">
<p class="cat-cont ">Find the <br>Perfect Helmet</p>
</div>
<a class="shopbtn" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-helmets.html">shop now !</a></div>