<div class="cat1-block">
<div class="cat1-block1">
<div class="cat11-block">
<img class="desktop" src="{{media url="bannerimage/block1img1.jpg"}}">
<img class="mobile" style="display:none;" src="{{media url="bannerimage/block1img1.jpg"}}">
<div class="block-cont firstbk">
<p class="cat-cont center">Find the <br>Protech Stick</p>
</div>
<a class="shopbtn center firstbk" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey.html">shop now !</a></div>
<div class="cat11-block">
<img class="desktop" src="{{media url="bannerimage/block1img2.jpg"}}">
<img class="mobile" style="display:none;" src="{{media url="bannerimage/block1img2.jpg"}}">
<div class="block-cont center firstbk">
<p class="cat-cont">Be Smart<br>Protech Your Head</p>
</div>
<a class="shopbtn center firstbk" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/hockey-helmets.html">shop now !</a></div>
</div>
<div class="cat12-block">
<img class="desktop" src="{{media url="bannerimage/block1img3.jpg"}}">
<img class="mobile" style="display:none;" src="{{media url="bannerimage/block1img3.jpg"}}">
<div class="block-cont firstbk">
<p class="cat-cont ">Perfect Stick <br>for Perfect Shot</p>
</div>
<a class="shopbtn firstbk" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/composite-sticks.html">shop now !</a></div>
</div>
<div class="cat14-block">
<img class="desktop" src="{{media url="bannerimage/block1img4.jpg"}}">
<img class="mobile" style="display:none;" src="{{media url="bannerimage/block1img4.jpg"}}">
<div class="block-cont center">
<p class="cat-cont left-bnr">Covered from<br>Head to Toe</p>
</div>
<a class="shopbtn bottom firstbk" href="http://v2.m2.sportszonecanada.com/team-sports-hockey/hockey/shoulder-pads.html">shop now !</a></div>